### PR TITLE
Add compatibility with 222.*

### PR DESCRIPTION
**Pull request by lilithium-hydride**
I don't know how to (or if I even can) run the theme compatibility checker myself, so apologies if there's more work to be done than a simple version number bump.

### CODE REVIEW

**Comment by jonmorgs** [comment]
Thank you for this! I'm away right now but I'll see what I can do to review this on Sunday!

**Comment by jonmorgs** [comment]
It looks like we have two options for this, upload a compiled version of the plugin to the marketplace page on the JetBrains website:
image
Or, try using this GitHub action https://github.com/marketplace/actions/intellij-plugin-verifier. I'll try enabling this now.

**Comment by jonmorgs** [comment]
I've built and tested this locally and it's working. The updated build has been uploaded to JetBrains marketplace and is awaiting approval.

I'll create another issue to automate the validation of this & create an artifact with the plugin .jar file to be uploaded to the marketplace.

Thanks again for this, @lilithium-hydride, and sorry I took so long to validate it!

**Comment by lilithium-hydride** [comment]
No worries, I'm glad it's working! I agree that automation is the best way forward with this, since Jetbrains' programs care so much about version numbers instead of looking at API differences.

**Pull request merged**
